### ISSUE TITLE
Question on optuna terminology

### ISSUE THREAD

**Issue by blurLake** [araffin/rl-baselines-zoo#101]
Hi, I am using zoo on my customized environment. In the terminal, I have some lines in the printout that "Trial XXX pruned". Does it mean that those trials are clearly worse than the best one so far, that the system just skips those combinations?

**Comment by araffin** [comment]
Hello,
This is an optuna question, so please read optuna documentation: https://optuna.readthedocs.io/en/stable/tutorial/pruning.html
