### ISSUE TITLE
What is the best initial values for the parameters in the .yml? [question]

### ISSUE THREAD

**Issue by toksis** [araffin/rl-baselines-zoo#103]
Hello,

I am using ACKTR and using the optima to have the obtain the optimum values. What should be the best initial values in the acktr.yml. Right now I just copy paste some of the values there.

```python
# not tuned
forex-v0:
  # env_wrapper: utils.wrappers.MyForexEnv
  n_envs: 8
  n_steps: 128
  n_timesteps: !!float 1e6
  policy: 'MlpPolicy'
  gamma: 0.99
  lr_schedule: 'constant'
```

**Comment by araffin** [comment]
Hello,

I'm not sure to understand your question, but it is probably answered in our [guide](https://stable-baselines.readthedocs.io/en/master/guide/rl_tips.html)

**Comment by toksis** [comment]
I mean what are the initial values of the hyperparameters when you do an -optimize on train.py, you will look to .yml to get the initial values of the hyperparameters. What are the initial values you put in the yml?

 
```python
        data_frame = hyperparam_optimization(args.algo, create_model, create_env, n_trials=args.n_trials,
                                             n_timesteps=n_timesteps, hyperparams=hyperparams,
                                             n_jobs=args.n_jobs, seed=args.seed,
                                             sampler_method=args.sampler, pruner_method=args.pruner,
                                             verbose=args.verbose)
```

**Comment by araffin** [comment]
>What are the initial values you put in the yml?

Several answers to that.
First, most of the hyperparameters comes from the paper.
Then, on enviroments where they don't work, I either quickly tried to tune them manually or ran some automatic hyperparameter tuning using Optuna (cf README).
For more details on the methodology, you can check the " Hyperparameter Optimization" section of the [gSDE](https://arxiv.org/abs/2005.05719) paper.

When I say "tune manually", I mean that for instance, you usually don't need an entropy bonus on continuous control, hence the `ent_coef` set to zero.

**Comment by toksis** [comment]
It is clear now. This gives me direction. Thank you.
