### ISSUE TITLE
update the baseline for new envs? [feature request]

### ISSUE THREAD

**Issue by MartinaRuocco** [araffin/rl-baselines-zoo#105]
Hi, thank you for this project!

I'd like to suggest you update this baseline with some new Robotic envs, such as 
- [FetchSlideEnv](https://github.com/openai/gym/blob/c0860592f51b53c00ce57e00cb3a9195943847d9/gym/envs/robotics/fetch/slide.py) (MuJoCo)
- [Panda and iCub](https://github.com/robotology-playground/pybullet-robot-envs) (PyBullet) 

it would also be cool to develop the Gym Environments for the [pybullet_robots](https://github.com/erwincoumans/pybullet_robots) such as:
- Turtlebot
- Sawyer
- Baxter 
- Boston Dynamics Atlas
- (...)

but I know that this is not the purpose of this project.

**Comment by araffin** [comment]
>FetchSlideEnv (MuJoCo)

This requires a license but I would be open to merge a PR with a trained agent (as in #53 ).

>Panda and iCub (PyBullet)

This project is still in alpha. But you can use it by customising slightly the rl zoo (or passing `--gym-packages`, cf example in the README).
