### ISSUE TITLE
[feature request] Install Zoo as a package

### ISSUE THREAD

**Issue by brendenpetersen** [araffin/rl-baselines-zoo#107]
It would be great to be able to install Zoo as a package/module (even better would be one registered to PyPI) so that I can access things like `utils` from other projects.

Until then I think my options are:
1. Use `sys.path.append(ZOO_REPOSITORY_ROOT)`.
2. Add my own `setup.py`.
3. Copy/link the code to `site-packages`.

None of these are great options when I'd like my project to view Zoo as a dependency.

**Comment by araffin** [comment]
Hello,
I understand your issue. However, the rl zoo is not really meant to be a package.
My main concern is that the current repo is quite big because of the trained agents, which is not the case anymore in the newest version of the zoo: https://github.com/DLR-RM/rl-baselines3-zoo.

>None of these are great options when I'd like my project to view Zoo as a dependency.

If you have a custom version of the zoo that is online (with a `setup.py`, you can always write it as a pip dependency:
```
pip install git+https://github.com/DLR-RM/rl-baselines3-zoo
```
would work ;) (with a proper `setup.py`)

**Comment by brendenpetersen** [comment]
@araffin Thanks for the reply. Yes, I was afraid that was going to be your answer :P Though it's understandable given that there is data in the repo. I was just hoping to be able to use it as a dependency without maintaining a fork with `setup.py`.

When you say "with a proper `setup.py`", do you mean I'd have to write one inside (a fork of) zoo? Or I could mangle my own project's `setup.py` to install zoo as a package (which doesn't have `setup.py`).

Also, I was not aware of https://github.com/DLR-RM/rl-baselines3-zoo. Or even stable-baselines3. Thanks!

**Comment by araffin** [comment]
i meant a `setup.py` in your fork.

>Also, I was not aware of https://github.com/DLR-RM/rl-baselines3-zoo. Or even stable-baselines3.

oh...we should advertise it more, we are close to a 1.0 (the library is already usable, we mostly need to polish several aspects)

**Comment by araffin** [comment]
Good news for you, I'll be migrating most of the utils (wrappers and callbacks) to the [sb3 contrib](https://github.com/Stable-Baselines-Team/stable-baselines3-contrib) package ;)

**Comment by brendenpetersen** [comment]
@araffin Awesome! Thanks so much for letting me know!!

**Comment by araffin** [comment]
now done in now done in https://github.com/DLR-RM/rl-baselines3-zoo/releases
