### ISSUE TITLE
Can we use it with Tenserflow 2.3.1 ?

### ISSUE THREAD

**Issue by deepakraina99** [araffin/rl-baselines-zoo#110]
When I run the enjoy.py file, I get the following error:
```
ModuleNotFoundError: No module named 'tensorflow.contrib'
```

After googling this error, I found that this only works with Tensorflow 1.x.x versions

**Comment by araffin** [comment]
Hello,

As mentioned in the doc, SB2 officially only support TF1. There is an unofficial port, see https://github.com/hill-a/stable-baselines/issues/1012 .
Our next major version, [Stable-Baselines3](https://github.com/DLR-RM/stable-baselines3) supports PyTorch.

**Comment by deepakraina99** [comment]
Thanks for the information.

**Comment by amexn-me** [comment]
Have you tried any workaround?

**Comment by deepakraina99** [comment]
No

**Comment by amexn-me** [comment]
I see. I tried downgrading TF to 1.15 like araffin said and it works for now.
