### ISSUE TITLE
Why during the evaluation VecNormalize stats arenot loaded from the current training stats? 

### ISSUE THREAD

**Issue by kartikpaigwar** [araffin/rl-baselines-zoo#111]

**Comment by araffin** [comment]
Hello,
I guess the answer lies here: https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/common/callbacks.py#L299

Btw, I would recommend you to use SB3 now ;) 
SB3: https://github.com/DLR-RM/stable-baselines3
Associated zoo: https://github.com/DLR-RM/rl-baselines3-zoo
