### ISSUE TITLE
[feature request]Add Mujoco-Gym since mujoco is free now

### ISSUE THREAD

**Issue by im-Kitsch** [araffin/rl-baselines-zoo#118]
Hi,

I would ask that if you would like to add support of mujoco gym like Ant-v2..., before it's not possible since it's commercial software but now mujoco is free now. 

best regards.

**Comment by araffin** [comment]
Hello,
sounds good, but that would be in https://github.com/DLR-RM/rl-baselines3-zoo

**Comment by im-Kitsch** [comment]
I will dump it in stable baselines 3
