### ISSUE TITLE
Installation od dependencies

### ISSUE THREAD

**Issue by testerpce** [araffin/rl-baselines-zoo#15]
My System is Ubuntu 16.04
Core i3
4 GB RAM
Laptop Integrated Graphics
HP Laptop

When I try installing the dependency using the command given below:
pip install stable-baselines>=2.2.1 box2d box2d-kengz pyyaml pybullet==2.1.0 pytablewriter

It gives the following error:
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-org3fV/stable-baselines/

I looked it up online and found they needed me to update setuptools. I updated setuptools using pip upgrade but it is still giving the same results.

**Comment by araffin** [comment]
Hello,
can you try to install only stable-baselines ?

```
pip install stable-baselines
```

and if it does not work can you try to install it from source (see [doc](https://stable-baselines.readthedocs.io/en/master/guide/install.html#bleeding-edge-version)) ?
