### ISSUE TITLE
missing dependency to the given Colab

### ISSUE THREAD

**Issue by marknabil** [araffin/rl-baselines-zoo#21]
**The bug**
running the first ```!python train.py --algo a2c --env CartPole-v1 --n-timesteps 100000``` throws error : cannot import optuna 

**System Info**
Running the ready given colab

** Solution **
Add ```!pip install optuna``` to the _install dependencies_ section

**Comment by araffin** [comment]
Thanks, I forgot to update the colab after merging the PR...
should be fixed now ;)
