### ISSUE TITLE
AttributeError: module 'train' has no attribute '__path__'

### ISSUE THREAD

**Issue by patterntrade** [araffin/rl-baselines-zoo#27]
Baselines Zoo

Following the example scripts on the GitHub welcome page.

```
./run_docker_cpu.sh python -m train.py --algo ppo2 --env MountainCar-v0 -n 50000 -optimize --n-trials 1000 --n-jobs 2 \   --sampler random --pruner median

python -m train.py --algo ppo2 --env MountainCar-v0 -n 50000 -optimize --n-trials 1000 --n-jobs 2 \   --sampler random --pruner median
```
Both give the same error msg:

`... Error while finding module specification for 'train.py' (AttributeError: module 'train' has no attribute '__path__') #27`

**System Info**
* Mac 10.14.4 (Mojave)
* Python 3.6.8

**Additional context**
Other scripts, like 
`./run_docker_cpu.sh python train.py --algo ppo2 --env CartPole-v1`
run OK.

**Comment by araffin** [comment]
Hello,

There seems to be a typo in the readme. This should be `python train.py` (without the -m)

**Comment by patterntrade** [comment]
Error stemming from writing

`...  python -m train.py ...`

Instead of just

`...  python -m train ...`

Perhaps the documentation could be updated accordingly?

Thanks for a GREAT code project in constant development, especially appreciating the hyper parameter tuning now included.

**Comment by araffin** [comment]
>Perhaps the documentation could be updated accordingly?

Yep, will be fixed in the next PR (HER-support)
