### ISSUE TITLE
BreakoutNoFrameskip-v4 in ppo2 does not match

### ISSUE THREAD

**Issue by QuXinghuaNTU** [araffin/rl-baselines-zoo#44]
When I try to load the pkl file from ppo2 folder (under trained_agents), I got this error:
TypeError: Expected float32 passed to parameter 'value' of op 'Assign', got 'model/c1/w:0' of type 'str' instead.

After checking the folder, I found that the description for BreakoutNoFrameskip-v4.pkl is td3.
I think there may exist some mistakes.

**Comment by araffin** [comment]
Hello,

Please fill in the issue template.

the following command runs perfectly fine:
```
 python enjoy.py --algo ppo2 --env BreakoutNoFrameskip-v4
```
