### ISSUE TITLE
Error "ImportError: DLL load failed" on Windows 10

### ISSUE THREAD

**Issue by sytelus** [araffin/rl-baselines-zoo#46]
I got the following error in train.py in Windows 10 when running statement `from mpi4py import MPI`:

```
ImportError: DLL load failed: The specified procedure could not be found.
```
The solution was to uninstall mpi4py package, install [Microsoft MPI 10.0](https://www.microsoft.com/en-us/download/details.aspx?id=57467) and then reinstall mpi4py. 

I think it might be good to document that people should first install Microsoft MPI 10.0. Even better, just don't import mpi4py if everything is on single machine :).

More: https://stackoverflow.com/a/58653569/207661

**Comment by araffin** [comment]
Hello,

Thanks for the pointer, but in fact this is already [documented](https://stable-baselines.readthedocs.io/en/master/guide/install.html#windows-10)

However, the current state of the zoo requires mpi even though stable-baselines can installed without it now. So I would appreciate a PR in the same spirit of what we do [here](https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/__init__.py) to make mpi optional for the zoo.

**Comment by araffin** [comment]
MPI is now optional since #60
