### ISSUE TITLE
Running average file (obs_rms.pkl, ret_rms.pkl) for Humanoid-v2?

### ISSUE THREAD

**Issue by gtatiya** [araffin/rl-baselines-zoo#5]
When making an env for 'HumanoidBulletEnv-v0' using `create_test_env`, Running average files are loaded from `stats_path` directory.

I tried loading env without it, but the acts like as it is not trained at all, but was able to walk when I load Running average files.

I've trained Mujoco's 'Humanoid-v2' using PPO with same hyper parameters provided by you in `ppo2.yml` and the rewards also improves over time.

But, when I render the trained 'Humanoid-v2', the acts like it is not trained.

I think, it's because I need to load the 'Humanoid-v2' with Running average files.
**Could you please provide Running average files for 'Humanoid-v2'.**

I tried loading 'HumanoidBulletEnv-v0' Running average files for 'Humanoid-v2' env, but I got this error:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-7bfe2d31eb5a> in <module>
      7 
      8 # Enjoy trained agent
----> 9 obs = env.reset()
     10 running_reward = 0.0
     11 ep_len = 0

~/anaconda2/envs/py3_6/lib/python3.6/site-packages/stable_baselines/common/vec_env/vec_normalize.py in reset(self)
     87             self.old_obs = obs
     88         self.ret = np.zeros(self.num_envs)
---> 89         return self._normalize_observation(obs)
     90 
     91     def save_running_average(self, path):

~/anaconda2/envs/py3_6/lib/python3.6/site-packages/stable_baselines/common/vec_env/vec_normalize.py in _normalize_observation(self, obs)
     63             if self.training:
     64                 self.obs_rms.update(obs)
---> 65             obs = np.clip((obs - self.obs_rms.mean) / np.sqrt(self.obs_rms.var + self.epsilon), -self.clip_obs,
     66                           self.clip_obs)
     67             return obs

ValueError: operands could not be broadcast together with shapes (1,376) (44,) 
```

**Comment by araffin** [comment]
Hello,
(Apparently I forgot to set up github issue template, but now, it's done...)

>But, when I render the trained 'Humanoid-v2', the acts like it is not trained.

Can you provide the command lines you used? Otherwise, it will be hard for me to help you.

>I think, it's because I need to load the 'Humanoid-v2' with Running average files.

when `normalize` is set to true, the running average will be automatically computed and saved.

> Could you please provide Running average files for 'Humanoid-v2'.

I don't plan to support `Humanoid-v2` as it requires mujoco which is a non free physics engine (and therefore cannot be tested with travis). Moreover, as I said before, the running average are computed automatically during training.

>I tried loading 'HumanoidBulletEnv-v0' Running average files for 'Humanoid-v2' env, but I got this error:

Yes, those two environments are different.

**Comment by gtatiya** [comment]
> 
> 
> Hello,
> (Apparently I forgot to set up github issue template, but now, it's done...)
> 
> > But, when I render the trained 'Humanoid-v2', the acts like it is not trained.
> 
> Can you provide the command lines you used? Otherwise, it will be hard for me to help you.
> 
> > I think, it's because I need to load the 'Humanoid-v2' with Running average files.
> 
> when `normalize` is set to true, the running average will be automatically computed and saved.
> 
> > Could you please provide Running average files for 'Humanoid-v2'.
> 
> I don't plan to support `Humanoid-v2` as it requires mujoco which is a non free physics engine (and therefore cannot be tested with travis). Moreover, as I said before, the running average are computed automatically during training.
> 
> > I tried loading 'HumanoidBulletEnv-v0' Running average files for 'Humanoid-v2' env, but I got this error:
> 
> Yes, those two environments are different.
> 
> EDIT: The current hyperparameters are not tuned enough for HumanoidBulletEnv-v0 yet. The reward improves, but it is not currently sufficient to solve the task.

Thanks for answering.

I used `VecNormalize()` when initializing the agent and after training I used `env.save_running_average(log_dir)` to save running average.

So, basically I'm doing this: https://gist.github.com/araffin/722b1e0da4064107797480a37643f331

Now, 'Humanoid-v2' agent performs better after training, but still can't really walk far.

I tried the hyper-parameters for 'HumanoidBulletEnv-v0' mentioned in https://github.com/araffin/rl-baselines-zoo/blob/5302a6bcfcdb121f34ffc202b967cf0cc8b39494/hyperparams/ppo2.yml

But, the agent can’t really learn to walk.
When I loaded trained agent using `python enjoy.py --algo ppo2 --env HumanoidBulletEnv-v0 --folder trained_agents/ -n 5000`
The agent is performing much better.

**I was wondering what hyper-parameters did you used to train this trained agent.**

BTW, thanks for creating this repo. It is excellent work!! :)

Thanks
