### ISSUE TITLE
Deprecation warning latest optuna version

### ISSUE THREAD

**Issue by jheffez** [araffin/rl-baselines-zoo#56]
Using latest optuna and running training results in multiple warnings:
`The use of `optuna.structs.TrialPruned` is deprecated. Please use `optuna.exceptions.TrialPruned` instead`

The following is a simple fix. in file utils\hyperparams_opt.py, change line 176 
`raise optuna.structs.TrialPruned()`
with:
`raise optuna.exceptions.TrialPruned()`

**Comment by araffin** [comment]
Hello,

I would appreciate a PR that fixes this issue ;) (but maybe maintaining backward compatibility (depending on when `optuna.exceptions` was introduced))
