### ISSUE TITLE
[question] Tuning Gym env variable?

### ISSUE THREAD

**Issue by jarlva** [araffin/rl-baselines-zoo#58]
In Gym, it's possible to pass arguments to the env when making it. I.e.,:
`env = gym.make('Myrl-v0', **params)`
Is it possible to tune a gym env variable with baseline-zoo train (or otherwise)?

**Comment by araffin** [comment]
hello,

it is currently not possible with the current rl zoo version, but you can easily allow it on a custom version of the zoo.
