### ISSUE TITLE
How to connect to container by EG remmina

### ISSUE THREAD

**Issue by patterntrade** [araffin/rl-baselines-zoo#6]
Have rl-baselines-zoo, GPU edition. Am running:

sudo docker run --runtime=nvidia -it basezoo bash
[sudo] password for hh: 
+ Xvfb :1 -screen 0 1024x768x24
+ export DISPLAY=:1
+ DISPLAY=:1
+ display=1
+ file=/tmp/.X11-unix/X1
+ sleep 1
++ seq 1 10
+ for i in '$(seq 1 10)'
+ '[' -e /tmp/.X11-unix/X1 ']'
+ break
+ '[' -e /tmp/.X11-unix/X1 ']'
+ exec bash
root@e62f057cb381:/# 

Portainer gives me an IP address, but no port info.

Evidently, a display is created, supposedly so I can connect from outside. And it would be quite helpful.

Have I understood this correctly? If so - how do I connect with EG remmina?

Help is much appreciated. Thank you!

**Comment by araffin** [comment]
Hello,
What is EG remmina?
Btw, it seems that you are trying to have an X window and this should be done when calling docker run. However, for me, i did not succeed yet to do so.
