### ISSUE TITLE
BipedalWalkerHardcore-v3

### ISSUE THREAD

**Issue by xkianteb** [araffin/rl-baselines-zoo#66]
Is it possible to have pre-trained BipedalWalkerHardcore-v3 agent with ppo2 added to the repo? Given the bug found in BipedalWalkerHardcore-v2?

**Comment by araffin** [comment]
Hello,
I will do a symlink to use the previously trained model as they worked also on the newest version.
I tried to retrain the agent but i did not get better results yet.
