### ISSUE TITLE
[Question] TD3 on FetchReach?

### ISSUE THREAD

**Issue by bycn** [araffin/rl-baselines-zoo#67]
I ran with the hyperparameters given for FetchReach TD3, and it wasn't able to solve perfectly in 25k timesteps like written — can someone verify that this is the case?

**Comment by araffin** [comment]
Hello,
how many run did you do?
did you try increasing the budget ?

**Comment by araffin** [comment]
I just tried with the [sb3 zoo](https://github.com/DLR-RM/rl-baselines3-zoo), and it works as expected...

For the current zoo, the normalization support is probably missing...
