### ISSUE TITLE
Docker repos missing files

### ISSUE THREAD

**Issue by patterntrade** [araffin/rl-baselines-zoo#7]
Have rl-baselines-zoo, GPU edition, pulled, not built.

Trying to run:

docker run -it --runtime=nvidia --rm --network host --ipc=host --name test --mount src="$(pwd)",target=/root/code/stable-baselines,type=bind araffin/stable-baselines bash -c 'cd /root/code/stable-baselines/ && pytest tests/'

Am running:

sudo docker run --runtime=nvidia -it  araffin/stable-baselines bash

Traversing into /root/code/, the directory is empty. It seems there is something wrong about the repository. Similar issues with the rl-zoo image.

I have little experience with docker, so I might well have missed something.

Kind regards

**Comment by araffin** [comment]
Hello,
Did you try running experiments with the shell script?
```
./run_docker_gpu.sh python train.py --algo ppo2 --env CartPole-v1
```

I am not 100% that the gpu image works (i have to fix a bug where tf is installed without gpu support, however the cpu image works , it used for continuous integration.

**Comment by patterntrade** [comment]
The GPU image doesn`t work, error msg like:

...
line 35, in <module>
    from tensorflow.python.keras import backend
  File "/root/venv/lib/python3.5/site-packages/tensorflow/python/keras/backend/__init__.py", line 22, in <module>
    from tensorflow.python.keras._impl.keras.backend import abs
ImportError: cannot import name 'abs'

Resolved by in the container:
source venv/bin/activate
pip install keras
pip install --upgrade tensorflow-gpu

Now it works!

Thanks for setting up this repository and the docker images, very helpful.

Merry Christmas!

:-)

**Comment by araffin** [comment]
Ok, I'll try to update the image then.

**Comment by araffin** [comment]
Hello again,
I updated the docker image, it should be fixed now, can you confirm this?

**Comment by araffin** [comment]
Are you using this dockerfile: https://github.com/araffin/rl-baselines-zoo/blob/master/docker/Dockerfile.gpu ?

Stable-Baselines is installed [here](https://github.com/araffin/rl-baselines-zoo/blob/master/docker/Dockerfile.gpu#L24)

The built image: https://hub.docker.com/r/araffin/rl-baselines-zoo

**Comment by patterntrade** [comment]
Hi! Thanks for replying so quickly.

No, I was using stable-baselines. I’ll get the RL-zoo image and try it out.

Still, it means that the documentation of stable-baselines needs to be updated, or the Dockerfiles/images need to be changed.¨

Kind regards


On 23 January 2019 at 20:34:23, Antonin RAFFIN (notifications@github.com) wrote:

Are you using this dockerfile: https://github.com/araffin/rl-baselines-zoo/blob/master/docker/Dockerfile.gpu ?

Stable-Baselines is installed here

The built image: https://hub.docker.com/r/araffin/rl-baselines-zoo

**Comment by araffin** [comment]
The doc is already updated ... cf https://stable-baselines.readthedocs.io/en/master/guide/install.html#using-docker-images
"
If you are looking for docker images with stable-baselines already installed in it, we recommend using images from RL Baselines Zoo.

Otherwise, the following images contained all the dependencies for stable-baselines but not the stable-baselines package itself. They are made for development.
"

**Comment by patterntrade** [comment]
Hi!

Have twice now tried to run this on Ubuntu 18 desktop, two different installations, once natively, once with Docker (run_docker_gpu.sh). The image I’m using is araffin/rl-baselines-zoo. With both installations I have this issue:

Fatal server error:
(EE) Cannot establish any listening sockets - Make sure an X server isn't already running(EE) 
++ seq 1 10
+ for i in '$(seq 1 10)'
+ '[' -e /tmp/.X11-unix/X1 ']'
+ echo 'Waiting for /tmp/.X11-unix/X1 to be created (try 1/10)'
Waiting for /tmp/.X11-unix/X1 to be created (try 1/10)
+ sleep 1
+ for i in '$(seq 1 10)'
+ '[' -e /tmp/.X11-unix/X1 ‘]'

and so forth (see below).

On the first installation, I thought I’d removed some lock files before. I’ve scoured the web for solutions to this issue, haven’t found anything. Would appreciate any ideas on how to address this.

Kind regards


REPOSITORY                 TAG                 IMAGE ID            CREATED             SIZE
araffin/rl-baselines-zoo   latest              c799b5127cf3        9 days ago          3.85GB
nvidia/cuda                9.0-base            74f5aea45cf6        2 months ago        134MB


sudo bash run_docker_gpu.sh python train.py --algo ppo2 --env CartPole-v1
Executing in the docker (gpu image):
python train.py --algo ppo2 --env CartPole-v1
+ export DISPLAY=:1
+ DISPLAY=:1
+ display=1
+ file=/tmp/.X11-unix/X1
+ sleep 1
+ Xvfb :1 -screen 0 1024x768x24
_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
_XSERVTransMakeAllCOTSServerListeners: server already running
(EE) 
Fatal server error:
(EE) Cannot establish any listening sockets - Make sure an X server isn't already running(EE) 
++ seq 1 10
+ for i in '$(seq 1 10)'
+ '[' -e /tmp/.X11-unix/X1 ']'
+ echo 'Waiting for /tmp/.X11-unix/X1 to be created (try 1/10)'
Waiting for /tmp/.X11-unix/X1 to be created (try 1/10)
+ sleep 1
+ for i in '$(seq 1 10)'
+ '[' -e /tmp/.X11-unix/X1 ']'
+ echo 'Waiting for /tmp/.X11-unix/X1 to be created (try 2/10)'
Waiting for /tmp/.X11-unix/X1 to be created (try 2/10)
+ sleep 2
+ for i in '$(seq 1 10)'
+ '[' -e /tmp/.X11-unix/X1 ']'
+ echo 'Waiting for /tmp/.X11-unix/X1 to be created (try 3/10)'
Waiting for /tmp/.X11-unix/X1 to be created (try 3/10)
+ sleep 3
+ for i in '$(seq 1 10)'
+ '[' -e /tmp/.X11-unix/X1 ']'
+ echo 'Waiting for /tmp/.X11-unix/X1 to be created (try 4/10)'
Waiting for /tmp/.X11-unix/X1 to be created (try 4/10)
+ sleep 4
+ for i in '$(seq 1 10)'
+ '[' -e /tmp/.X11-unix/X1 ']'
+ echo 'Waiting for /tmp/.X11-unix/X1 to be created (try 5/10)'
Waiting for /tmp/.X11-unix/X1 to be created (try 5/10)
+ sleep 5
+ for i in '$(seq 1 10)'
+ '[' -e /tmp/.X11-unix/X1 ']'
+ echo 'Waiting for /tmp/.X11-unix/X1 to be created (try 6/10)'
Waiting for /tmp/.X11-unix/X1 to be created (try 6/10)
+ sleep 6
+ for i in '$(seq 1 10)'
+ '[' -e /tmp/.X11-unix/X1 ']'
+ echo 'Waiting for /tmp/.X11-unix/X1 to be created (try 7/10)'
Waiting for /tmp/.X11-unix/X1 to be created (try 7/10)
+ sleep 7
+ for i in '$(seq 1 10)'
+ '[' -e /tmp/.X11-unix/X1 ']'
+ echo 'Waiting for /tmp/.X11-unix/X1 to be created (try 8/10)'
Waiting for /tmp/.X11-unix/X1 to be created (try 8/10)
+ sleep 8
+ for i in '$(seq 1 10)'
+ '[' -e /tmp/.X11-unix/X1 ']'
+ echo 'Waiting for /tmp/.X11-unix/X1 to be created (try 9/10)'
Waiting for /tmp/.X11-unix/X1 to be created (try 9/10)
+ sleep 9
+ for i in '$(seq 1 10)'
+ '[' -e /tmp/.X11-unix/X1 ']'
+ echo 'Waiting for /tmp/.X11-unix/X1 to be created (try 10/10)'
Waiting for /tmp/.X11-unix/X1 to be created (try 10/10)
+ sleep 10
+ '[' -e /tmp/.X11-unix/X1 ']'
+ echo 'Timing out: /tmp/.X11-unix/X1 was not created'
Timing out: /tmp/.X11-unix/X1 was not created
+ exit 1
m@ub-desk:~/rl-baselines-zoo$ 


lshw
WARNING: you should run this program as super-user.
ub-desk                     
    description: Computer
    width: 64 bits
    capabilities: smp vsyscall32
  *-core
       description: Motherboard
       physical id: 0
     *-memory
          description: System memory
          physical id: 0
          size: 47GiB
     *-cpu
          product: Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz
          vendor: Intel Corp.
          physical id: 1
          bus info: cpu@0
          size: 1199MHz
          capacity: 3800MHz
          width: 64 bits


On 23 January 2019 at 20:48:33, Antonin RAFFIN (notifications@github.com) wrote:

The doc is already updated ... cf https://stable-baselines.readthedocs.io/en/master/guide/install.html#using-docker-images
"
If you are looking for docker images with stable-baselines already installed in it, we recommend using images from RL Baselines Zoo.

Otherwise, the following images contained all the dependencies for stable-baselines but not the stable-baselines package itself. They are made for development.
"

**Comment by patterntrade** [comment]
Hi!

Thanks for your speedy answer!

Tried the cpu image, same error.

Thanks for the hint about the post installation, did that.

So, it must be something with my system. Will have to figure that out.

Kind regards.


On 27 January 2019 at 18:26:21, Antonin RAFFIN (notifications@github.com) wrote:

Ok, did you try the cpu image?
If it does not work with the cpu image, I'm afraid the problem may come from your machine, because the cpu image is tested at each push on Travic CI.
What you are seeing is the entrypoint.sh trying to create a fake X server in order to be able to launch any env that requires one.
Btw, why do you have to use sudo? Did you follow the post-installation?

**Comment by patterntrade** [comment]
Hi again.

I modified entrypoint.sh, rebuilt the GPU image, ran the container: 

ee@ub-desk:~/Desktop/docker$ bash run_docker_gpu.sh python train.py --algo ppo2 --env CartPole-v1
Executing in the docker (gpu image):
python train.py --algo ppo2 --env CartPole-v1
Traceback (most recent call last):
  File "train.py", line 11, in <module>
    from stable_baselines.common import set_global_seeds
  File "/root/venv/lib/python3.5/site-packages/stable_baselines/__init__.py", line 4, in <module>
    from stable_baselines.a2c import A2C
  File "/root/venv/lib/python3.5/site-packages/stable_baselines/a2c/__init__.py", line 1, in <module>
    from stable_baselines.a2c.a2c import A2C
  File "/root/venv/lib/python3.5/site-packages/stable_baselines/a2c/a2c.py", line 5, in <module>
    import tensorflow as tf
  File "/root/venv/lib/python3.5/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/root/venv/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 63, in <module>
    from tensorflow.python.framework.framework_lib import *  # pylint: disable=redefined-builtin
  File "/root/venv/lib/python3.5/site-packages/tensorflow/python/framework/framework_lib.py", line 104, in <module>
    from tensorflow.python.framework.importer import import_graph_def
  File "/root/venv/lib/python3.5/site-packages/tensorflow/python/framework/importer.py", line 32, in <module>
    from tensorflow.python.framework import function
  File "/root/venv/lib/python3.5/site-packages/tensorflow/python/framework/function.py", line 36, in <module>
    from tensorflow.python.ops import resource_variable_ops
  File "/root/venv/lib/python3.5/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 35, in <module>
    from tensorflow.python.ops import variables
  File "/root/venv/lib/python3.5/site-packages/tensorflow/python/ops/variables.py", line 40, in <module>
    class Variable(checkpointable.CheckpointableBase):
AttributeError: module 'tensorflow.python.training.checkpointable' has no attribute 'CheckpointableBase'

Pretty sure this is an error in the code, unrelated to the fake X server issue.

Do you have any suggestions?

Kind regards


On 27 January 2019 at 22:37:24, Bjørn A. Helland-Hansen (bjornprivate@runbox.com) wrote:

Hi!

Thanks for your speedy answer!

Tried the cpu image, same error.

Thanks for the hint about the post installation, did that.

So, it must be something with my system. Will have to figure that out.

Kind regards.


On 27 January 2019 at 18:26:21, Antonin RAFFIN (notifications@github.com) wrote:

Ok, did you try the cpu image?
If it does not work with the cpu image, I'm afraid the problem may come from your machine, because the cpu image is tested at each push on Travic CI.
What you are seeing is the entrypoint.sh trying to create a fake X server in order to be able to launch any env that requires one.
Btw, why do you have to use sudo? Did you follow the post-installation?

**Comment by patterntrade** [comment]
ADDITIONAL INFO> BUILD LOG GPU IMAGE

```
Get:332 http://archive.ubuntu.com/ubuntu xenial/universe amd64 libopenmpi-dev amd64 1.10.2-8ubuntu1 [537 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 225 MB in 7min 7s (527 kB/s)

Successfully installed virtualenv-16.3.0
You are using pip version 8.1.1, however version 19.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Using base prefix '/usr'
New python executable in /root

Collecting joblib (from stable-baselines==2.4.0)
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /simple/joblib/
  Downloading https://files.pythonhosted.org/packages/49/d9/4ea194a4c1d0148f9446054b9135f47218c23ccc6f649aeb09fab4c0925c/joblib-0.13.1-py2.py3-none-any.whl (278kB)

Successfully built html5lib
tensorflow 1.12.0 has requirement tensorboard<1.13.0,>=1.12.0, but you'll have tensorboard 1.8.0 which is incompatible.
Installing collected packages: html5lib, bleach, tensorboard, tensorflow-gpu
```

So docker build gave some warnings, but for some reason built the image anyway. I`m not sure that explains the issues in the previous entry or not.
