### ISSUE TITLE
or this part is compiled to machine language?

### ISSUE THREAD

**Issue by alanyuwenche** [araffin/rl-baselines-zoo#71]
Thanks for your great job.

However, I can’t find the source code for different algorithm. For example, I can only train an agent by a2c but can’t check how to code A2C. Do I miss something or this part is compiled to machine language?

**Comment by araffin** [comment]
Hello,

It seems you are quite new to python. As mentioned in the README, we are using the [stable-baselines](https://github.com/hill-a/stable-baselines) package, where all the algorithms are defined.
