### ISSUE TITLE
import DDPG failed

### ISSUE THREAD

**Issue by JohannesUl** [araffin/rl-baselines-zoo#81]
Consider adding something like
```
try:
    import mpi4py
except ImportError:
    mpi4py = None

if mpi4py is not None:
    from stable_baselines import DDPG
    from stable_baselines.ddpg import AdaptiveParamNoiseSpec, NormalActionNoise, OrnsteinUhlenbeckActionNoise
del mpi4py
```
in hyperparameters_opt.py. This would avoid errors if stable-baselines 2.10.0 is installed without mpi and would comply with https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/__init__.py

Best,
Johannes

**Comment by araffin** [comment]
Hello,
I would appreciate a PR that solves that issue ;)
