### ISSUE TITLE
Using the monitor wrapper with ppo2 

### ISSUE THREAD

**Issue by meric-sakarya** [araffin/rl-baselines-zoo#95]
I am trying to use the Monitor Wrapper to better visualize the results of my training. I added the following line to the ppo2.yml file: env_wrapper: stable_baselines.bench.monitor. It did not work and I received this error when trying to restart the training:
![2020-07-25 (1)](https://user-images.githubusercontent.com/38434300/88459126-2e44da00-ce93-11ea-9278-edb0b71bc6df.png)

I also tried to copy the file Monitor from stable baselines to the wrappers.py file in my Zoo folder and use that directly but that also did not work:
![2020-07-25 (2)](https://user-images.githubusercontent.com/38434300/88459945-0c4e5600-ce99-11ea-8191-477bb471325e.png)

**Comment by araffin** [comment]
If you use the zoo, the env is automatically wrapped with a Monitor wrapper.

Please fill the issue template properly next time (using markdown codeblock).

**Comment by meric-sakarya** [comment]
The environment uses more than one environment and therefore the graph results on Tensorboard are wacky. Just like in this issue hill-a/stable-baselines#143.
![2020-07-25](https://user-images.githubusercontent.com/38434300/88460409-643a8c00-ce9c-11ea-8a67-f06cf5ebe203.png)

**Comment by araffin** [comment]
>The environment uses more than one environment and therefore the graph results on Tensorboard are wacky. Just like in this issue hill-a/stable-baselines#143.

This is unrelated to the original question.
You should take a look at the documentation first to plot the information displayed in the terminal: https://stable-baselines.readthedocs.io/en/master/guide/tensorboard.html#legacy-integration
